config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :styles
  resources :layers
  resources :territorials
  resources :modulos
  get 'home/index'
  
  
  root 'home#index'
end

app/models/map.rb
class Map < ApplicationRecord
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: %i[ show edit update destroy ]

  # GET /maps or /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1 or /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps or /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to map_url(@map), notice: "Map was successfully created." }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1 or /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to map_url(@map), notice: "Map was successfully updated." }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1 or /maps/1.json
  def destroy
    @map.destroy!

    respond_to do |format|
      format.html { redirect_to maps_url, notice: "Map was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def map_params
      params.require(:map).permit(:target, :maxZoom, :minZoom, :initialZoom, :srid, :public, :longitude, :latitude)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: map) do |form| %>
      <% if map.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

          <ul>
            <% map.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
          </ul>
        </div>
      <% end %>

              <div class="mb-3">
                      <%= form.label :target, style: "display: block", class: "form-label" %>
            <%= form.text_field :target, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :maxZoom, style: "display: block", class: "form-label" %>
            <%= form.text_field :maxZoom, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :minZoom, style: "display: block", class: "form-label" %>
            <%= form.text_field :minZoom, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :initialZoom, style: "display: block", class: "form-label" %>
            <%= form.text_field :initialZoom, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :srid, style: "display: block", class: "form-label" %>
            <%= form.text_field :srid, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :public, style: "display: block", class: "form-label" %>
            <%= form.text_field :public, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :longitude, style: "display: block", class: "form-label" %>
            <%= form.text_field :longitude, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :latitude, style: "display: block", class: "form-label" %>
            <%= form.text_field :latitude, class: "form-control" %>
                  </div>
      
      <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/maps/_map.html.erb
<div id="<%= dom_id map %>">
  <p>
    <strong>Target:</strong>
    <%= map.target %>
  </p>

  <p>
    <strong>Maxzoom:</strong>
    <%= map.maxZoom %>
  </p>

  <p>
    <strong>Minzoom:</strong>
    <%= map.minZoom %>
  </p>

  <p>
    <strong>Initialzoom:</strong>
    <%= map.initialZoom %>
  </p>

  <p>
    <strong>Srid:</strong>
    <%= map.srid %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= map.public %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= map.longitude %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= map.latitude %>
  </p>

</div>

app/views/maps/edit.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"> <h1>Editar map</h1></h4>
  <div class="row">
    <!-- Basic -->
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
        </h5>
        <div class="card-body">   
           <%= render "form", map: @map %>
        <br>

        <div>
        <%= link_to "Show this map", @map %> |
        <%= link_to "Back to maps", maps_path %>
        </div>
           </div>
      </div>
    </div>
  </div>
</div>

app/views/maps/index.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
               <h4 class="fw-bold py-3 mb-4">Maps</h4>
              <div class="row">
                <!-- Basic -->
                <div class="col-md-12 mb-4">
                  <div class="card">
                    <h5 class="card-header">
                    <%= link_to "Add map", new_map_path %>
                    </h5>
              <div class="card-body">
                <div class=" container-xxl flex-grow-1 container-p-y p-5">
                  <table class="table"  >
                    <thead>
                      <tr>
                         
                          <th>Target</th>
                        
                          <th>Max Zoom</th>
                        
                          <th>Min Zoom</th>
                        
                          <th>Initial Zoom</th>
                        
                          <th>Srid</th>
                        
                          <th>Public</th>
                        
                          <th>Longitude</th>
                        
                          <th>Latitude</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                <% @maps.each do |map| %>
                    
                      <td><%= map.target %></td>
                    
                      <td><%= map.maxZoom %></td>
                    
                      <td><%= map.minZoom %></td>
                    
                      <td><%= map.initialZoom %></td>
                    
                      <td><%= map.srid %></td>
                    
                      <td><%= map.public %></td>
                    
                      <td><%= map.longitude %></td>
                    
                      <td><%= map.latitude %></td>
                             
                        <td><%= link_to 'Show', map %></td>
                        <td><%= link_to 'Edit', edit_map_path(map) %></td>
                        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% end %>          
                    </tbody>
                  </table>
                  
                  </div>
                </div>  
              </div>
      </div>
    </div>
  </div>
</div>

app/views/maps/new.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4">Map</h4>

  <div class="row">
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
        </h5>
        <div class="card-body">
        <h1>New map</h1>
        <%= render "form", map: @map %>
        <br>
        <div>
        <%= link_to "Back to maps", maps_path %>
        </div>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/maps/show.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4">Detalhes do Map</h4>
  <div class="row">
    <!-- Basic -->
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
       
        </h5>
        <div class="card-body">
        <p style="color: green"><%= notice %></p>
            <%= render @map %>
            <div>
            <%= link_to "Edit this map", edit_map_path(@map) %> |
            <%= link_to "Back to maps", maps_path %>
            <%= button_to "Destroy this map", @map, method: :delete %>
           </div>
         
        </div>
      </div>
    </div>
  </div>
</div>