config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :styles
  resources :layers
  resources :territorials
  resources :modulos
  get 'home/index'
  
  
  root 'home#index'
end

app/models/style.rb
class Style < ApplicationRecord
    has_many :layers
    belongs_to :fill, class_name: "Fill", foreign_key: "fill_id", optional: true
    belongs_to :stroke, class_name: "Stroke", foreign_key: "stroke_id", optional: true
  end
  

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: %i[ show edit update destroy ]

  # GET /styles or /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1 or /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles or /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to style_url(@style), notice: "Style was successfully created." }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1 or /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to style_url(@style), notice: "Style was successfully updated." }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1 or /styles/1.json
  def destroy
    @style.destroy!

    respond_to do |format|
      format.html { redirect_to styles_url, notice: "Style was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def style_params
      params.require(:style).permit(:opacity, :fill_id, :stroke_id)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: style) do |form| %>
      <% if style.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

          <ul>
            <% style.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
          </ul>
        </div>
      <% end %>

              <div class="mb-3">
                      <%= form.label :opacity, style: "display: block", class: "form-label" %>
            <%= form.text_field :opacity, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :fill_id, style: "display: block", class: "form-label" %>
            <%= form.text_field :fill_id, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :stroke_id, style: "display: block", class: "form-label" %>
            <%= form.text_field :stroke_id, class: "form-control" %>
                  </div>
      
      <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/styles/_style.html.erb
<div id="<%= dom_id style %>">
  <p>
    <strong>Opacity:</strong>
    <%= style.opacity %>
  </p>

  <p>
    <strong>Fill:</strong>
    <%= style.fill_id %>
  </p>

  <p>
    <strong>Stroke:</strong>
    <%= style.stroke_id %>
  </p>

</div>

app/views/styles/edit.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"> <h1>Editar style</h1></h4>
  <div class="row">
    <!-- Basic -->
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
        </h5>
        <div class="card-body">   
           <%= render "form", style: @style %>
        <br>

        <div>
        <%= link_to "Show this style", @style %> |
        <%= link_to "Back to styles", styles_path %>
        </div>
           </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/index.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
               <h4 class="fw-bold py-3 mb-4">Styles</h4>
              <div class="row">
                <!-- Basic -->
                <div class="col-md-12 mb-4">
                  <div class="card">
                    <h5 class="card-header">
                    <%= link_to "Add style", new_style_path %>
                    </h5>
              <div class="card-body">
                <div class=" container-xxl flex-grow-1 container-p-y p-5">
                  <table class="table"  >
                    <thead>
                      <tr>
                         
                          <th>Opacity</th>
                        
                          <th>Fill</th>
                        
                          <th>Stroke</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                <% @styles.each do |style| %>
                    
                      <td><%= style.opacity %></td>
                    
                      <td><%= style.fill_id %></td>
                    
                      <td><%= style.stroke_id %></td>
                             
                        <td><%= link_to 'Show', style %></td>
                        <td><%= link_to 'Edit', edit_style_path(style) %></td>
                        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% end %>          
                    </tbody>
                  </table>
                  
                  </div>
                </div>  
              </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/new.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4">Style</h4>

  <div class="row">
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
        </h5>
        <div class="card-body">
        <h1>New style</h1>
        <%= render "form", style: @style %>
        <br>
        <div>
        <%= link_to "Back to styles", styles_path %>
        </div>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/styles/show.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4">Detalhes do Style</h4>
  <div class="row">
    <!-- Basic -->
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
       
        </h5>
        <div class="card-body">
        <p style="color: green"><%= notice %></p>
            <%= render @style %>
            <div>
            <%= link_to "Edit this style", edit_style_path(@style) %> |
            <%= link_to "Back to styles", styles_path %>
            <%= button_to "Destroy this style", @style, method: :delete %>
           </div>
         
        </div>
      </div>
    </div>
  </div>
</div>