config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :styles
  resources :layers
  resources :territorials
  resources :modulos
  get 'home/index'
  
  
  root 'home#index'
end

app/models/layer.rb
class Layer < ApplicationRecord

  belongs_to :style
  belongs_to :map

end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  before_action :set_layer, only: %i[ show edit update destroy ]

  # GET /layers or /layers.json
  def index
    @layers = Layer.all
  end

  # GET /layers/1 or /layers/1.json
  def show
  end

  # GET /layers/new
  def new
    @layer = Layer.new
  end

  # GET /layers/1/edit
  def edit
  end

  # POST /layers or /layers.json
  def create
    @layer = Layer.new(layer_params)

    respond_to do |format|
      if @layer.save
        format.html { redirect_to layer_url(@layer), notice: "Layer was successfully created." }
        format.json { render :show, status: :created, location: @layer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layers/1 or /layers/1.json
  def update
    respond_to do |format|
      if @layer.update(layer_params)
        format.html { redirect_to layer_url(@layer), notice: "Layer was successfully updated." }
        format.json { render :show, status: :ok, location: @layer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1 or /layers/1.json
  def destroy
    @layer.destroy!

    respond_to do |format|
      format.html { redirect_to layers_url, notice: "Layer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @layer = Layer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def layer_params
      params.require(:layer).permit(:name, :layer, :show_legend, :type, :source, :srid, :display, :primitive, :imagery, :style_id, :ordem, :map_id)
    end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">
    <%= form_with(model: layer) do |form| %>
      <% if layer.errors.any? %>
        <div class="alert alert-danger">
          <h2><%= pluralize(layer.errors.count, "error") %> prohibited this layer from being saved:</h2>

          <ul>
            <% layer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
          </ul>
        </div>
      <% end %>

              <div class="mb-3">
                      <%= form.label :name, style: "display: block", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :layer, style: "display: block", class: "form-label" %>
            <%= form.text_field :layer, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :show_legend, style: "display: block", class: "form-label" %>
            <%= form.text_field :show_legend, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :type, style: "display: block", class: "form-label" %>
            <%= form.text_field :type, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :source, style: "display: block", class: "form-label" %>
            <%= form.text_field :source, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :srid, style: "display: block", class: "form-label" %>
            <%= form.text_field :srid, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :display, style: "display: block", class: "form-label" %>
            <%= form.text_field :display, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :primitive, style: "display: block", class: "form-label" %>
            <%= form.text_field :primitive, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :imagery, style: "display: block", class: "form-label" %>
            <%= form.text_field :imagery, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :style_id, style: "display: block", class: "form-label" %>
            <%= form.text_field :style_id, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :ordem, style: "display: block", class: "form-label" %>
            <%= form.text_field :ordem, class: "form-control" %>
                  </div>
              <div class="mb-3">
                      <%= form.label :map_id, style: "display: block", class: "form-label" %>
            <%= form.text_field :map_id, class: "form-control" %>
                  </div>
      
      <div class="mb-3">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layers/_layer.html.erb
<div id="<%= dom_id layer %>">
  <p>
    <strong>Name:</strong>
    <%= layer.name %>
  </p>

  <p>
    <strong>Layer:</strong>
    <%= layer.layer %>
  </p>

  <p>
    <strong>Show legend:</strong>
    <%= layer.show_legend %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= layer.type %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= layer.source %>
  </p>

  <p>
    <strong>Srid:</strong>
    <%= layer.srid %>
  </p>

  <p>
    <strong>Display:</strong>
    <%= layer.display %>
  </p>

  <p>
    <strong>Primitive:</strong>
    <%= layer.primitive %>
  </p>

  <p>
    <strong>Imagery:</strong>
    <%= layer.imagery %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= layer.style_id %>
  </p>

  <p>
    <strong>Ordem:</strong>
    <%= layer.ordem %>
  </p>

  <p>
    <strong>Map:</strong>
    <%= layer.map_id %>
  </p>

</div>

app/views/layers/edit.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"> <h1>Editar layer</h1></h4>
  <div class="row">
    <!-- Basic -->
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
        </h5>
        <div class="card-body">   
           <%= render "form", layer: @layer %>
        <br>

        <div>
        <%= link_to "Show this layer", @layer %> |
        <%= link_to "Back to layers", layers_path %>
        </div>
           </div>
      </div>
    </div>
  </div>
</div>

app/views/layers/index.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
               <h4 class="fw-bold py-3 mb-4">Layers</h4>
              <div class="row">
                <!-- Basic -->
                <div class="col-md-12 mb-4">
                  <div class="card">
                    <h5 class="card-header">
                    <%= link_to "Add layer", new_layer_path %>
                    </h5>
              <div class="card-body">
                <div class=" container-xxl flex-grow-1 container-p-y p-5">
                  <table class="table"  >
                    <thead>
                      <tr>
                         
                          <th>Name</th>
                        
                          <th>Layer</th>
                        
                          <th>Show Legend</th>
                        
                          <th>Type</th>
                        
                          <th>Source</th>
                        
                          <th>Srid</th>
                        
                          <th>Display</th>
                        
                          <th>Primitive</th>
                        
                          <th>Imagery</th>
                        
                          <th>Style</th>
                        
                          <th>Ordem</th>
                        
                          <th>Map</th>
                        
                      </tr>
                    </thead>
                    <tbody>
                <% @layers.each do |layer| %>
                    
                      <td><%= layer.name %></td>
                    
                      <td><%= layer.layer %></td>
                    
                      <td><%= layer.show_legend %></td>
                    
                      <td><%= layer.type %></td>
                    
                      <td><%= layer.source %></td>
                    
                      <td><%= layer.srid %></td>
                    
                      <td><%= layer.display %></td>
                    
                      <td><%= layer.primitive %></td>
                    
                      <td><%= layer.imagery %></td>
                    
                      <td><%= layer.style_id %></td>
                    
                      <td><%= layer.ordem %></td>
                    
                      <td><%= layer.map %></td>
                             
                        <td><%= link_to 'Show', layer %></td>
                        <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
                        <td><%= link_to 'Destroy', layer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <% end %>          
                    </tbody>
                  </table>
                  
                  </div>
                </div>  
              </div>
      </div>
    </div>
  </div>
</div>

app/views/layers/new.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4">Layer</h4>

  <div class="row">
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
        </h5>
        <div class="card-body">
        <h1>New layer</h1>
        <%= render "form", layer: @layer %>
        <br>
        <div>
        <%= link_to "Back to layers", layers_path %>
        </div>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layers/show.html.erb
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4">Detalhes do Layer</h4>
  <div class="row">
    <!-- Basic -->
    <div class="col-md-12 mb-4">
      <div class="card">
        <h5 class="card-header">
       
        </h5>
        <div class="card-body">
        <p style="color: green"><%= notice %></p>
            <%= render @layer %>
            <div>
            <%= link_to "Edit this layer", edit_layer_path(@layer) %> |
            <%= link_to "Back to layers", layers_path %>
            <%= button_to "Destroy this layer", @layer, method: :delete %>
           </div>
         
        </div>
      </div>
    </div>
  </div>
</div>